=== biocaddie/WG3-MetadataSpecifications/json-schemas/dataset_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "DATS Dataset Schema",
    "description": "A set of dimensions about an entity being observed. A collection of data, published or curated by a single agent, and available for access or download in one or more formats (from DCAT: http://www.w3.org/TR/vocab-dcat/#Class:_Dataset). A body of structured information describing some topic(s) of interest (from: http://schema.org/Dataset).",
    "type": "object",
    "properties": {
        "@context": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                }
            ]
        },
        "@type": { "type": "string", "enum": [ "Dataset"] },
        "identifier": {
            "$ref": "identifier_info_schema.json#"
        },
        "alternateIdentifiers": {
            "description": "Alternate identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "alternate_identifier_info_schema.json#"
            }
        },
        "relatedIdentifiers": {
            "description": "Related identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "related_identifier_info_schema.json#"
            }
        },
        "title" : {
            "description" : "The name of the dataset, usually one sentece or short description of the dataset.",
            "type" : "string"
        },
        "description" : {
            "description": "A textual narrative comprised of one or more statements describing the dataset.",
            "type" : "string"
        },
        "dates" : {
            "description": "Relevant dates for the datasets, a date must be added, e.g. creation date or last modification date should be added.",
            "type" : "array",
            "items" : {
                "$ref" : "date_info_schema.json#"
            }
        },
        "storedIn" : {
            "description": "The data repository hosting the dataset.",
            "$ref": "data_repository_schema.json#"
        },
        "spatialCoverage": {
            "description": "The geographical extension and span covered by the dataset and its measured dimensions/variables.",
            "type" : "array",
            "items" : {
                "$ref" : "place_schema.json#"
            }
        },
        "types" : {
            "description": "A term, ideally from a controlled terminology, identifying the dataset type or nature of the data, placing it in a typology",
            "type" : "array",
            "items" : {
                "$ref" : "data_type_schema.json#"
            },
            "minItems" : 1
        },
        "availability": {
            "description": "A qualifier indicating the different types of availability for a dataset (available, unavailable, embargoed, available with restriction, information not available).",
            "type": "string"
        },
        "refinement": {
            "description": "A qualifier to describe the level of data processing of the dataset and its distributions.",
            "type": "string"
        },
        "aggregation": {
            "description": "A qualifier indicating if the entity represents an 'instance of dataset' or a 'collection of datasets'.",
            "type": "string"
        },
        "privacy": {
            "description": "A qualifier to describe the data protection applied to the dataset. This is relevant for clinical data.",
            "type": "string"
        },
        "distributions" : {
            "description": "The distribution(s) by which datasets are made available (for example: mySQL dump).",
            "type" : "array",
            "items" : {
                "$ref" : "dataset_distribution_schema.json#"
            }
        },
        "dimensions" : {
            "description": "The different dimensions (granular components)  making up a dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "dimension_schema.json#"
            }
        },
        "primaryPublications" : {
            "description": "The primary publication(s) associated with the dataset, usually describing how the dataset was produced.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citations" : {
            "description": "The publication(s) that cite this dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citationCount": {
            "description": "The number of publications that cite this dataset (enumerated in the citations property)",
            "type": "integer"
        },
        "producedBy" : {
            "description": "A study process which generated a given dataset, if any.",
            "$ref" : "study_schema.json#"
        },
        "creators" : {
            "description": "The person(s) or organization(s) which contributed to the creation of the dataset.",
            "type" : "array",
            "items" : {
                "oneOf": [
                    {"$ref" : "person_schema.json#"},
                    {"$ref" : "organization_schema.json#"}
                ]
            },
            "minItems" : 1
        },
        "licenses": {
            "description": "The terms of use of the dataset.",
            "type": "array",
            "items": {
                "$ref": "license_schema.json#"
            }
        },
        "isAbout": {
            "description" : "Different entities (biological entity, taxonomic information, disease, molecular entity, anatomical part, treatment) associated with this dataset.",
            "type": "array",
            "items": {
                "anyOf": [
                    {"$ref" : "biological_entity_schema.json#"},
                    {"$ref" : "taxonomic_info_schema.json#"},
                    {"$ref" : "disease_schema.json#"},
                    {"$ref" : "molecular_entity_schema.json#"},
                    {"$ref" : "anatomical_part_schema.json#"},
                    {"$ref" : "treatment_schema.json#"},
                    {"$ref" : "annotation_schema.json#"}
                ]
            }
        },
        "hasPart" : {
            "description": "A Dataset that is a subset of this Dataset; Datasets declaring the 'hasPart' relationship are considered a collection of Datasets, the aggregation criteria could be included in the 'description' field.",
            "type": "array",
            "items": {
                "$ref" : "dataset_schema.json#"
            }
        },
        "acknowledges" : {
            "description": "The grant(s) which funded and supported the work reported by the dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "grant_schema.json#"
            }
        },
        "keywords" : {
            "description": "Tags associated with the dataset, which will help in its discovery.",
            "type": "array",
            "items": {
                "$ref" : "annotation_schema.json#"
            }
        },
        "extraProperties": {
            "description": "Extra properties that do not fit in the previous specified attributes. ",
            "type": "array",
            "items": {
                "$ref" : "category_values_pair_schema.json#"
            }
        }
    },
    "additionalProperties": false,
    "required" : [ "title", "types", "creators" ]
}

=== biocaddie/WG3-MetadataSpecifications/json-instances/datacommons/dats_phs001143.json
{
  "@type": "Dataset",
  "relatedIdentifiers": [
    {
      "identifier": "phs001143.v1.p1",
      "identifierSource": "dbGAP",
      "relationType": "parentStudy"
    }
  ],
  "identifier": {
    "identifier": "phs001143.v1.p1"
  },
  "dates": [
    {
      "date": "20160608",
      "type": {
        "value": "created"
      }
    },
    {
      "date": "20170608",
      "type": {
        "value": "modified"
      }
    }
  ],
  "title": "NHLBI TOPMed: The Genetics and Epidemiology of Asthma in Barbados",
  "description": "Asthma is a complex disease where the interplay between genetic factors and environmental exposures influences susceptibility and disease prognosis. Asthmatics of African descent tend to have more severe asthma and more severe clinical symptoms than individuals of European ancestry. The baseline prevalence of asthma in Barbados is high (~20%), and from admixture analyses, we have determined that the proportion of African ancestry among Barbadian founders is similar to U.S. African Americans, rendering this a unique population to disentangle the genetic basis for asthma disparities among African ancestry populations in general. We therefore performed whole genome sequencing on 1,100 individuals from the Barbados Genetics of Asthma Study (BAGS), in order to generate additional discovery of rare and structural variants that may control risk to asthma.",
  "storedIn": {
    "@type": "DataRepository",
    "name": "dbGaP"
  },
  "producedBy": {
    "@type": "Study",
    "types": [
      {
        "value": ""
      }
    ],
    "name": "",
    "studyGroups": [
      {
        "@type": "StudyGroup",
        "name": "Exchange Area (IRB)",
        "extraProperties": [
          {
            "category": "ConsentAbbrev",
            "values": [
              "EA-IRB"
            ]
          },
          {
            "values": [
              "Yes"
            ],
            "category": "IrbRequired"
          },
          {
            "values": [
              "Use by NHLBI WGS study investigators only. There is one consent group for this study: GRU-IRB. Use of the data is limited only by the terms of the model Data Use Certification. Requestor must provide documentation of local IRB approval."
            ],
            "category": "UseLimitation"
          }
        ],
        "identifier": {
          "identifier": "999"
        }
      }
    ],
    "input": [
      {
        "@type": "Material",
        "name": "",
        "bearerOfDisease": [
          {
            "@type": "Disease",
            "name": "Asthma",
            "extraProperties": [
              {
                "category": "vocab_source",
                "values": [
                  "MESH"
                ]
              }
            ]
          }
        ]
      }
    ],
    "schedulesActivity": [
      {
        "@type": "Activity",
        "description": "TOPMed Whole Genome Sequencing Project",
        "extraProperties": [
          {
            "category": "urlToHtml",
            "values": [
              "http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs001143.v1.p1&phd=6969"
            ]
          },
          {
            "category": "urlToXml",
            "values": [
              "http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetDocumentXml.cgi?document_id=phd006969.2"
            ]
          },
          {
            "values": [
              "public"
            ],
            "category": "displayStatus"
          },
          {
            "values": [
              "public"
            ],
            "category": "xmlStatus"
          }
        ],
        "keywords": [
          {
            "value": "protocol"
          }
        ],
        "startDate": {
          "date": "20170403",
          "type": {
            "value": "start"
          }
        },
        "identifier": {
          "identifier": "phd006969.2"
        },
        "dates": [
          {
            "date": "20170608",
            "type": {
              "value": "modified"
            }
          }
        ],
        "relatedIdentifiers": [
          {
            "identifier": "TOPMed_for_dbGaP_April2016_v5_final.docx",
            "identifierSource": "",
            "relationType": ""
          }
        ],
        "name": "TOPMed Whole Genome Sequencing Project"
      },
      {
        "@type": "Activity",
        "description": "Asthma / Affection Status",
        "extraProperties": [
          {
            "category": "urlToHtml",
            "values": [
              "http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs001143.v1.p1&phd=6974"
            ]
          },
          {
            "category": "urlToXml",
            "values": [
              "http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetDocumentXml.cgi?document_id=phd006974.1"
            ]
          },
          {
            "values": [
              "public"
            ],
            "category": "displayStatus"
          },
          {
            "values": [
              "public"
            ],
            "category": "xmlStatus"
          }
        ],
        "keywords": [
          {
            "value": "protocol"
          }
        ],
        "startDate": {
          "date": "20161101",
          "type": {
            "value": "start"
          }
        },
        "identifier": {
          "identifier": "phd006974.1"
        },
        "dates": [
          {
            "date": "20161101",
            "type": {
              "value": "modified"
            }
          }
        ],
        "relatedIdentifiers": [
          {
            "identifier": "Asthma.docx",
            "identifierSource": "",
            "relationType": ""
          }
        ],
        "name": "Asthma / Affection Status"
      }
    ],
    "selectionCriteria": [
      {
        "value": "DNA samples of 1100 individuals from 190 Barbados families were whole genome sequenced (asthma cases and controls). Among all cases, asthma was defined as both a reported history of asthma and a documented history of physician-diagnosed asthma (past or current). For each of the asthma studies, a standardized questionnaire based on either American Thoracic Society or International Study of Asthma and Allergy in Childhood questionnaires was administered by a clinical coordinator. The identity and relationships of individuals were checked using IBD estimates, and individuals were excluded if discrepant. Samples that failed whole genome sequencing quality control were also excluded."
      }
    ],
    "schedulesDataAcquisition": [
      {
        "@type": "DataAcquisition",
        "name": "",
        "uses": [
          {
            "@type": "Software",
            "name": ""
          }
        ]
      }
    ]
  },
  "creators": [
    {
      "@type": "Organization",
      "extraProperties": [
        {
          "category": "DacEmail",
          "values": [
            ""
          ]
        },
        {
          "category": "DacPhone",
          "values": [
            ""
          ]
        },
        {
          "category": "DacUrl",
          "values": [
            ""
          ]
        }
      ],
      "identifier": {
        "identifier": "0"
      },
      "name": "National Heart, Lung, and Blood Institute DAC",
      "abbreviation": "NHLBI"
    },
    {
      "@type": "Person",
      "affiliations": [
        {
          "@type": "Organization",
          "name": "University of Colorado, Denver, CO, USA"
        }
      ],
      "fullName": "Kathleen Barnes, PhD"
    }
  ],
  "licenses": [
    {
      "@type": "License",
      "extraProperties": [
        {
          "category": "para",
          "values": [
            "http://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=DUC&view_pdf&stacc=phs001143.v1.p1"
          ]
        },
        {
          "values": [
            "yes"
          ],
          "category": "Policy DisplayPublicSummary"
        },
        {
          "values": [
            "yes"
          ],
          "category": "DisplayResearchStatement"
        },
        {
          "category": "FileName",
          "values": [
            ""
          ]
        },
        {
          "category": "FilePath",
          "values": [
            "https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=DUC&view_pdf&stacc=phs001143.v1.p1"
          ]
        },
        {
          "category": "EmbargoLength",
          "values": [
            "0"
          ]
        },
        {
          "category": "PdfSupplementReqired",
          "values": [
            "yes"
          ]
        },
        {
          "category": "WeeksCancelRequest",
          "values": [
            "8"
          ]
        },
        {
          "category": "YearsUntilRenewal",
          "values": [
            "1"
          ]
        },
        {
          "category": "Configuration DisplayPublicSummary",
          "values": [
            "yes"
          ]
        }
      ],
      "identifier": {
        "identifier": "phs001143.v1.p1_policy"
      },
      "name": "Data Use Certificate"
    }
  ],
  "acknowledges": [],
  "primaryPublications": [
    {
      "@type": "Publication",
      "identifier": {
        "identifier": "pmid:19910028",
        "identifierSource": "pmid"
      },
      "publicationVenue": ""
    }
  ],
  "extraProperties": [
    {
      "values": [
        "NHLBI TOPMed: The Genetics and Epidemiology of Asthma in Barbados"
      ],
      "category": "StudyNameReportPage"
    }
  ],
  "distributions": [
    {
      "@type": "DatasetDistribution",
      "access": {
        "@type": "Access",
        "accessURL": "",
        "landingPage": ""
      }
    }
  ],
  "types": [
    {}
  ]
}
